name: ruby
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Run standard
        run: bundle exec rake standard

      - name: Run unit tests
        run: bundle exec rake spec

      - name: Install firebase tools
        run: |
          mkdir -p tools
          curl -o tools/firebase -L https://firebase.tools/bin/linux/latest
          chmod +rx tools/firebase

      - name: Run integration tests
        run: tools/firebase emulators:exec --only auth --project test-adminsdk-project 'bundle exec rake integration'
