name: ruby
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run standard
        run: bundle exec rake standard

      - name: Run unit tests
        run: bundle exec rake spec

      - name: Cache firebase tools
        uses: actions/cache@v2
        id: cache-firebase
        with:
          path: /usr/local/bin/firebase
          key: ${{ runner.os }}-firebase-tools

      - name: Install firebase tools
        if: steps.cache-firebase.outputs.cache-hit != 'true'
        run: curl -sL firebase.tools | bash

      - name: Run integration tests
        run: firebase emulators:exec --only auth --project test-adminsdk-project 'bunlde exec rake integration'
